### ISSUE TITLE
Error `invalid file name 'boot=casper'` when booting from an ISO created with Cubic version 2022.11.73.

### ISSUE THREAD

**Issue by skris88** [PJ-Singh-001/Cubic#130]
Hi,

The Cubic created ISO of a (un-customised) Xubuntu 64-bit 'copy' fails to boot. But a (also un-customised) older version of Xubuntu 32-bit 'copy' (non-UEFI) created ISO works.

These are striaght 'copies'; ie. no modifications were made to the distro, nothing was added or removed (just in case I was adding or removing something that might cause the problem).

The ISOs I tried were:

1. Xubuntu 18.04 Bionic Beaver (32-bit)
2. Xubuntu 20.04 Focal Fossa (64-bit)
3. Xubuntu 22.04 Jammy Jellyfish (64-bit)

Only Xubuntu 18.04 Bionic Beaver (32-bit) worked.

The other two had this error message:
error: invalid file name 'boot=casper'.
error: you need to load the kernel first.

Thanks!

Cheers,
Kris

**Comment by pjflament** [comment]
Same problem. 

Fresh download of ubuntu-22.04.1-desktop-amd64.iso loaded to a fresh install of cubic version 2022.11.73 running under vmlinuz-5.15.0-53-generic. Just added, under the cubic  virtual environment, a user with adduser, populated its home directory and wrote out ubuntu-22.04.1-2022.11.22-desktop-amd64.iso  .  Iso will boot neither under cubic "Test", nor with a USB iso onto a new machine. 

Appears related to a grub misconfiguration, but have not found where.

**Comment by PJ-Singh-001** [comment]
Kris,

I was not able to recreate this issue on my end, so I will need your help to debug this...

**Questions**

 1. How are you testing the customized ISO? (Are you using the [<kbd>Test</kbd> button](https://github.com/PJ-Singh-001/Cubic/wiki/Finish-Test-Page) on the [Finish page](https://github.com/PJ-Singh-001/Cubic/wiki/Finish-Page), are you testing the ISO in a virtual machine such as VirtualBox, or are you creating a USB stick?)
 2. Which operating system and version are you running Cubic from?
 3. What is the architecture of your host machine (32 bit or 64 bit)?
 4. What is the version of Cubic you are using (shown by the `cubic --version` command) ?

**See if this resolves the issue?**

Please try the following, and report your results.

On the [Boot tab](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#boot-tab) on the [Options page](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page), you will see a few files:

 1. `boot/grub/grub.cfg`
 2. `boot/grub/loopback.cfg`
 5. `isolinux/rqtxt.cfg`
 6. `isolinux/txt.cfg`

For this test, you can probably just modify `boot/grub/grub.cfg` and `boot/grub/loopback.cfg`.

Replace all occurrences of...

    boot=casper /casper/vmlinuz

...with...

    /casper/vmlinuz boot=casper

Then generate your ISO and test it.

**Comment by pjflament** [comment]
Indeed with cubic version 2022.06.72 running under  an install of ubuntu-20.04.3-desktop-amd64.iso the order in grub.cfg and loopback.cfg is as PJ Singh states, I find
`/casper/vmlinuz boot=casper`
With do-release-upgrade of ubuntu-20.04.3-desktop-amd64 to ubuntu-22.04.1-desktop-amd64 on the host, the same cubic version 2022.06.72 still gives the correct order.

Thus the accidental swapping of 
`/casper/vmlinuz boot=casper`
to
`boot=casper /casper/vmlinuz`
appears to occur between cubic version 2022.06.72 and version 2022.11.73 .

Manually swapping the order as suggested by PJ Singh works:  Iso will boot now both under cubic "Test", or with a USB iso onto a new machine.

Is this a _feature_ of cubic version 2022.11.73, or a minor bug?

Thanks PJ Singh for quick reply and solution.

**Comment by pjflament** [comment]
This was all done under 64 bit architecture.

**Comment by TorbenMartin** [comment]
![Bildschirmfoto zu 2022-11-23 10-05-19](https://user-images.githubusercontent.com/97087023/203507649-e279df31-c513-4a23-a5b7-9aee7b9c0f9d.png)

same problem. 

host: ubuntu 20.04.5
cubic version: 2022.11.73
iso: ubuntu 22.04.1

i try to change many thing. also created the casper folder. copy + symlink inside. but error is same all time

in /boot is no casper folder

**Comment by pjflament** [comment]
TorbenMartin you are  correct, but **you should not work** on /boot  in the virtual environment.

Instead,  you should go "Next" twice forward from the virtual environment, then you will see three tabs on top, "Kernel", "Preseed" and "Boot". Click on "Boot", and then you see the files grub.cfg and loopback.cfg. Then you can correct the order 
`boot=casper /casper/vmlinuz `
to
`/casper/vmlinuz boot=casper`
everywhere, and it will work.

This is exactly what  PJ Singh suggested and he deserves credit for having saved my day and deadline.

**Comment by TorbenMartin** [comment]
i recreated all. delete all. than start new. now it works with that solution. dont know my first try (same solution) not work...

**Comment by PJ-Singh-001** [comment]
Thanks for reporting this issue and for testing!

I should have a fix released within a few days, in the mean time, please [manually apply the correction as described above](https://github.com/PJ-Singh-001/Cubic/issues/130#issuecomment-1324596807).

This is only necessary for new projects. Once you've applied this fix for an existing project, you will not have to re-edit the grub boot configurations, since your change for `boot=` will be retained.

**Comment by skris88** [comment]
Hi,

I can wait. The customised distro I am trying to create is only required
after the Christmas holidays.

Thanks for your efforts.

Best regards,
Kris

**Comment by PJ-Singh-001** [comment]
Fix released in Cubic version 2022.12.74.

Please test and report any issues.

**Comment by Panja0** [comment]
> Fix released in Cubic version 2022.12.74.
> 
> Please test and report any issues.

I'm still having problems with v2022.12.74
Created a custom Kubuntu 22.04.1 ISO on Kubuntu 22.04.1 and with the latest Cubic version (as pointed above) and still having problems booting. I can get to the Grub (v2.04) screen but trying any option results in:
```
error: invalid magic number
error: you need to load the kernel first
```

**Comment by skris88** [comment]
Hi all,

I updated Cubic, and my customised ISO now worked perfectly first time off
a USB.

5 stars!

Thanks.

Please close my Ticket.

Cheers,
Kris

**Comment by PJ-Singh-001** [comment]
Please note, Cubic version 2022.12.74 will not correct this issue in the boot files of *existing projects created using version 2022.11.73*.

If you are creating a new project, however, you will not encounter the issue reported in this Bug, since Cubic will now correctly place the `boot=` parameter *after* the `vmlinuz` parameter.

For existing projects, please [manually correct the boot files as shown above](https://github.com/PJ-Singh-001/Cubic/issues/130#issuecomment-1324596807).

Alternatively, if you want Cubic to do this for you automatically, delete the `boot=` parameter in the boot files, click the <kbd>Back</kbd> button, then click the <kbd>Next</kbd>button. This will force Cubic to re-insert the `boot=` parameter in the correct position.
